### PR TITLE
Fix 1.9

### LINKED ISSUE #755: RNG not being seeded during precompilation
Maybe this needs to be moved to julia issues.

On nightly the following is failing
https://github.com/JuliaLang/PackageCompiler.jl/blob/8d71b02705a4ceae8ca1481d09107938f68b0d57/examples/MyApp/src/MyApp.jl#L73-L74

where myrand is a const in the module
https://github.com/JuliaLang/PackageCompiler.jl/blob/8d71b02705a4ceae8ca1481d09107938f68b0d57/examples/MyApp/src/MyApp.jl#L14

See https://github.com/JuliaLang/PackageCompiler.jl/actions/runs/3857713317/jobs/6575476152

@vchuravy is this known?

### PR DESCRIPTION
**Pull request by IanButterworth**
Closes #755 

#755 was due to the sysimage output process being launched with O2 vs the precompiled O3, so the caches were rejected, entering a state where `__init__` are not run and the RNG wasn't seeded. i.e. the test correctly caught the issue

### CODE REVIEW

**Comment by IanButterworth** [comment]
The remaining 1.9+ failure is https://github.com/JuliaLang/PackageCompiler.jl/issues/755

File: src/PackageCompiler.jl [hunk 1]
```diff
@@ -378,7 +378,7 @@ function create_sysimg_object_file(object_file::String,
     write(outputo_file, julia_code)
     # Read the input via stdin to avoid hitting the maximum command line limit
 
-    cmd = `$(get_julia_cmd()) --cpu-target=$cpu_target -O3 $sysimage_build_args
+    cmd = `JULIA_DEBUG=loading $(get_julia_cmd()) --cpu-target=$cpu_target -O3 $sysimage_build_args
```
Comment (KristofferC) [inline src/PackageCompiler.jl]: Does this work? Don't you need to use `withenv` or something?

Comment (IanButterworth) [reply src/PackageCompiler.jl]: No it doesn't work. I pushed a fix

**Comment by IanButterworth** [comment]
Locally on julia master I get `ERROR: Unable to find compatible target in system image.`

```
┌ Debug: running `/home/ian/Documents/GitHub/julia/usr/bin/julia --color=yes --startup-file=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' -O3 --sysimage=/home/ian/Documents/GitHub/julia/usr/lib/julia/sys.so --project=/tmp/jl_0fuMB7/MyApp --output-o=/tmp/jl_WTIp8zq32r.o /tmp/jl_uzSJWPaVwR`
└ @ PackageCompiler ~/Documents/GitHub/PackageCompiler.jl/src/PackageCompiler.jl:389
⠋ [00m:00s] PackageCompiler: compiling incremental system imageERROR: Unable to find compatible target in system image.
✖ [00m:00s] PackageCompiler: compiling incremental system image
filter = false: Error During Test at /home/ian/Documents/GitHub/PackageCompiler.jl/test/runtests.jl:64
  Got exception outside of a @test
  failed process: Process(`/home/ian/Documents/GitHub/julia/usr/bin/julia --color=yes --startup-file=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' -O3 --sysimage=/home/ian/Documents/GitHub/julia/usr/lib/julia/sys.so --project=/tmp/jl_0fuMB7/MyApp --output-o=/tmp/jl_WTIp8zq32r.o /tmp/jl_uzSJWPaVwR`, ProcessExited(1)) [1]
```

**Comment by DilumAluthge** [comment]
> Locally on julia master I get `ERROR: Unable to find compatible target in system image.`

Does your local Julia master include https://github.com/JuliaLang/julia/pull/48131?

**Comment by IanButterworth** [comment]
> Does your local Julia master include https://github.com/JuliaLang/julia/pull/48131?

Yeah it does. I'm on https://github.com/JuliaLang/julia/pull/48168

```
julia> versioninfo()
Julia Version 1.10.0-DEV.295
Commit bdf976b260* (2023-01-07 17:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 5950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 16 on 32 virtual cores
```

**Comment by DilumAluthge** [comment]
Does this mean that https://github.com/JuliaLang/julia/pull/48131 didn't completely fix https://github.com/JuliaLang/julia/issues/48111?

**Comment by IanButterworth** [comment]
I don't know. It didn't happen all the time.

Tests locally, where the error was `ERROR: Unable to find compatible target in system image.`
```
Test Summary:           | Pass  Fail  Error  Total      Time
PackageCompiler.jl      |   56     2      1     59  32m12.9s
  create_sysimage       |    3                   3   1m30.6s
  create_app            |   52     2      1     55  20m42.3s
    incremental = true  |                 1      1   1m10.6s
      filter = false    |                 1      1   1m10.6s
    incremental = false |   52     2            54  19m31.6s
      filter = true     |   26     1            27   9m49.7s
      filter = false    |   26     1            27   9m41.9s
```
Although I never saw this error
```
┌ Debug: Rejecting cache file /tmp/jl_aCrjdm/compiled/v1.9/LibSSH2_jll/K6mup_TmZuG.ji for LibSSH2_jll [29816b5a-b9ab-546f-933c-edad1886dfa8] since the flags are mismatched
│   cachefile_flags = 35
│   current_flags = 51
└ @ Base loading.jl:2526
```

but I did see a lot of
```
┌ Debug: Rejecting cache file /tmp/jl_LzuULE/compiled/v1.10/MKL_jll/DHEix_r71fR.ji for MKL_jll [856f044c-d86e-5d09-b602-aeab76dc8ba7] since pkgimage can't be loaded on this target
└ @ Base loading.jl:2565
```
which is checked after the flags check, so flag check appears to be passing locally.


I'm quite confused here..

**Comment by IanButterworth** [comment]
If it's informative I dumped `clone_targets` into the loading debug log
```
┌ Debug: Rejecting cache file /tmp/jl_YlNZqW/compiled/v1.10/Zlib_jll/xjq3Q_pQJwP.ji for Zlib_jll [83775a58-1f1d-513f-b197-d71354ab007a] since pkgimage can't be loaded on this target
│   clone_targets = UInt8[0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x03, 0x32, 0xd8, 0x36, 0x00, 0x00, 0x00, 0x00, 0x29, 0x01, 0x88, 0x21, 0x90, 0x06, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x61, 0x01, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x27, 0xdc, 0x63, 0x59, 0x00, 0x3a, 0x00, 0x41, 0x45, 0x03, 0x00, 0x08, 0x21, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x7a, 0x6e, 0x76, 0x65, 0x72, 0x33, 0x00, 0x00, 0x00, 0x00]
└ @ Base loading.jl:2564
```

**Comment by vchuravy** [comment]
What are you setting JULIA_CPU_TARGET to?

**Comment by IanButterworth** [comment]
During tests it appears to be the default 

https://github.com/JuliaLang/PackageCompiler.jl/blob/28cb6cb9be3409e91de4224c8c2ffce28042c354/src/PackageCompiler.jl#L33

File: src/PackageCompiler.jl [hunk 2]
```diff
@@ -247,9 +247,15 @@ end
 function ensurecompiled(project, packages, sysimage)
     length(packages) == 0 && return
     # TODO: Only precompile `packages` (should be available in Pkg 1.8)
-    cmd = `$(get_julia_cmd()) --sysimage=$sysimage -e 'using Pkg; Pkg.precompile()'`
+    cmd = if isdefined(Base, :Linking) && Base.JLOptions().use_pkgimages != 0
+        # if pkgimages -O3 is needed to match the -O3 of the sysimage generation
+        `$(get_julia_cmd()) -O3 --sysimage=$sysimage -e 'using Pkg; Pkg.precompile()'`
```
Comment (IanButterworth) [inline src/PackageCompiler.jl:252]: This branch isn't being hit on 1.9+ for some reason, causing the O2/3 mismatch

**Comment by IanButterworth** [comment]
pkgimages are somehow disabled in `ensurecompiled`... ??

```
┌ Debug: ensurecompiled
│   isdefined(Base, :Linking) = true
│   (Base.JLOptions()).use_pkgimages = 0
└ @ PackageCompiler ~/work/PackageCompiler.jl/PackageCompiler.jl/src/PackageCompiler.jl:250
```

**Comment by IanButterworth** [comment]
Ohhh.. `julia-runtest` is running with coverage, so the tests are being run without pkgimages. I guess just force -O3 on 1.9+ then. Assume pkgimages aren't disabled

**Comment by IanButterworth** [comment]
Ok, with coverage disabled (and thus pkgimages enabled) this is now hitting the issue I see locally 
```
┌ Debug: Rejecting cache file /tmp/jl_zmpJYV/compiled/v1.9/LibSSH2_jll/K6mup_XSlU0.ji for LibSSH2_jll [29816b5a-b9ab-546f-933c-edad1886dfa8] since pkgimage can't be loaded on this target
└ @ Base loading.jl:2538
```

**Comment by vchuravy** [comment]
> Ok, with coverage disabled (and thus pkgimages enabled and with -O3 set during precompilation) this is now hitting the issue I see locally
> 
> ```
> ┌ Debug: Rejecting cache file /tmp/jl_zmpJYV/compiled/v1.9/LibSSH2_jll/K6mup_XSlU0.ji for LibSSH2_jll [29816b5a-b9ab-546f-933c-edad1886dfa8] since pkgimage can't be loaded on this target
> └ @ Base loading.jl:2538
> ```

I am not sure I understand the issue here. Is the issue that we have a time-out since we are rejecting every cache file?

What is happening is that we create a pkgimage cachefile for a particular target (either native or multiversioning) and then have started a Julia session that uses a different target.
https://github.com/timholy/PkgCacheInspector.jl/pull/3

**Comment by vchuravy** [comment]
Maybe the right answer here is to run with `--pkgimage=no` it seems not to make sense to do all the extra work in the context of PackageCompiler.jl

Also I think you need to set the environment flag not the command line flag since Julia will complain.

**Comment by IanButterworth** [comment]
> Maybe the right answer here is to run with --pkgimage=no

Yeah. Especially given the sysimage will be built with -O3 and most people's existing pkgimage caches will be -O2.

**Comment by KristofferC** [comment]
If there is no chance to reuse the already precompiled files that a user has from an earlier `Pkg.precompile` then using pkg images seems pointless, yes.

**Comment by vchuravy** [comment]
I mean PackageCompiler will not re-use that information at all. It would be a big rewrite to have PackageCompiler turn into a linker of package images.

**Comment by KristofferC** [comment]
This is just for package load times. When you load a package into the process that outputs the sysimage, it will use a precompile file if such a file exist to speed up loading.

**Comment by IanButterworth** [comment]
Note if it doesn't find a usable cache it currently hits the bug where myrand is zero.

**Comment by KristofferC** [comment]
Yew, because `__init__` functions do not run in the sysimage process which means the RNG is not seeded. That is what that test is testing, that we load from a ji file (and thus the earlier Pkg.precompile was successful).

**Comment by IanButterworth** [comment]
> Also I think you need to set the environment flag not the command line flag since Julia will complain.

@vchuravy I couldn't find the environment flag (assuming the sysimage step will fail currently because of this)

**Comment by IanButterworth** [comment]
I'm surprised that 1.9 is passing but nightly is failing

**Comment by IanButterworth** [comment]
I'm keen to get this fixed because I can't fully test 1.9 in our stack before PackageCompiler works.

Given 1.9-nightly works here, I could try this branch, but I'd prefer to use a release.

**Comment by IanButterworth** [comment]
@vchuravy is the last commit what you meant on slack? And if so, is it backwards compatible, or do I need to only do this on 1.9+?

**Comment by vchuravy** [comment]
Should be backwards compatible. Everyone else just ignores it.

**Comment by IanButterworth** [comment]
hmm, then removing `--cpu-target` isn't backwards compatible. I'll push a fix

File: src/PackageCompiler.jl [hunk 3]
```diff
@@ -219,9 +223,15 @@ function create_fresh_base_sysimage(stdlibs::Vector{String}; cpu_target::String)
...
-                                    -g0 -O0 $compiler_source_path`
-            @debug "running $cmd"
+            cmd = if isdefined(Base, :Linking) # pkgimages feature flag
+                cmd = `$(get_julia_cmd()) --output-ji $tmp_corecompiler_ji -g0 -O0 $compiler_source_path`
+                @debug "running $cmd" JULIA_CPU_TARGET = cpu_target
+                addenv(cmd, "JULIA_CPU_TARGET" => cpu_target)
+            else
+                cmd = `$(get_julia_cmd()) --cpu-target $cpu_target --output-ji $tmp_corecompiler_ji
+                                        -g0 -O0 $compiler_source_path`
+                @debug "running $cmd"
```
Comment (IanButterworth) [inline src/PackageCompiler.jl:233]:
```suggestion
                @debug "running $cmd"
                cmd
```

**Comment by IanButterworth** [comment]
The handling here feels a bit messy, but as far as I understand it's now correct. 
The failures on nightly appear to require c-level changes.
Perhaps a tidyup/refactoring could follow when nightly is fixed.

So I'll merge and I think a patch release should be made
