### PR TITLE
Call `get_compiler_cmd()` at the beginning of `create_sysimage` and `create_app`

### LINKED ISSUE #677: Fail early if no compiler can be found?
If possible, it would perhaps be nice to detect the presence of a compiler before spending the time to build the system image?
```
✔ [07m:05s] PackageCompiler: compiling incremental system image
ERROR: LoadError: could not find a compiler, looked for g++, clang++, gcc and clang
```

### LINKED ISSUE #727: Check c++ compiler earlier
I just generated a sysimage, taking a lot of time, only to fail in the end because I was missing a c++ compiler.
Could a simple check be made in the start to avoid wasting time for users without a c++ compiler installed?

### PR DESCRIPTION
**Pull request by DilumAluthge**
That way, users will immediately get an error if a compiler cannot be found, instead of having to wait a long time before the error is thrown.

Replaces #769
Closes #769 
Closes #677 
Closes #727

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I'm not sure what the current state of CI is.

@IanButterworth Are these CI failures expected?

File: src/PackageCompiler.jl [hunk 1]
```diff
@@ -483,6 +483,7 @@ function create_sysimage(packages::Union{Nothing, Symbol, Vector{String}, Vector
                          compat_level::String="major",
                          extra_precompiles::String = "",
                          )
+    get_compiler_cmd()
```
Comment (IanButterworth) [inline src/PackageCompiler.jl:486]: Perhaps add a comment to explain why this is called in both locations but not used?

**Comment by IanButterworth** [comment]
1.6 won't pass. The rest should but there are gremlins

File: src/PackageCompiler.jl (hunk 1 above)
Comment (DilumAluthge) [reply src/PackageCompiler.jl:487]: Done!

File: src/PackageCompiler.jl [hunk 2]
```diff
@@ -483,6 +483,8 @@ function create_sysimage(packages::Union{Nothing, Symbol, Vector{String}, Vector
                          compat_level::String="major",
                          extra_precompiles::String = "",
                          )
+    # We call this at the very beginning to make sure that the user has a compiler available. Therefore, if no compiler is fiund, we throw an error immediately, instead of making the user wait a while before the error is thrown.
```
Comment (IanButterworth) [inline src/PackageCompiler.jl:486]: typo on found and linewidth
```suggestion
    # We call this at the very beginning to make sure that the user has a compiler available.  Therefore, if no compiler 
    # is found, we throw an error immediately, instead of making the user wait a while before the error is thrown.
```

File: src/PackageCompiler.jl [hunk 3]
```diff
@@ -748,6 +750,8 @@ function create_app(package_dir::String,
                     sysimage_build_args::Cmd=``,
                     include_transitive_dependencies::Bool=true)
     warn_official()
+    # We call this at the very beginning to make sure that the user has a compiler available. Therefore, if no compiler is fiund, we throw an error immediately, instead of making the user wait a while before the error is thrown.
```
Comment (IanButterworth) [inline src/PackageCompiler.jl:753]:
```suggestion
    # We call this at the very beginning to make sure that the user has a compiler available.  Therefore, if no compiler 
    # is found, we throw an error immediately, instead of making the user wait a while before the error is thrown.
```

**Review by IanButterworth — APPROVED** [review]
