### PR TITLE
Test suite: on Julia 1.6, remove `LLVMExtra_jll` from the `MyApp/Project.toml` file

### LINKED ISSUE #706: Tests are failing on Julia 1.6
https://github.com/JuliaLang/PackageCompiler.jl/runs/7175755312?check_suite_focus=true#step:4:340
```
InitError(mod=:LLVMExtra_jll, error=ErrorException("Cannot locate artifact 'LLVMExtra' in '/tmp/jl_s8rPQE/packages/LLVMExtra_jll/RuRRc/Artifacts.toml'"))
```

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #706

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -65,6 +81,9 @@ end
             @info "starting: create_app testset" incremental filter
             tmp_app_source_dir = joinpath(tmp, "MyApp")
             cp(app_source_dir, tmp_app_source_dir)
+            if is_julia_1_6
+                remove_llvmextras(joinpath(tmp_app_source_dir, "Project.toml"))
+            end
```
Comment (IanButterworth) [inline test/runtests.jl:86]:
```suggestion
            if is_julia_1_6
                # Issue #706 "Cannot locate artifact 'LLVMExtra'" on 1.6 so remove                
                remove_llvmextras(joinpath(tmp_app_source_dir, "Project.toml"))
            end
```

**Comment by IanButterworth** [comment]
This looks good to me, but I defer to @KristofferC

**Comment by DilumAluthge** [comment]
All 1.6 jobs are green. So let's give this a try and see how it goes.

We can always revert later if we decide we want to go on a different direction.
